---
dist: bionic
language: python
python:
  - 3.8

install:
  - python -m pip install -r ./requirements/dev.txt

script:
  - python -m pytest
  - python -m black --check --verbose .
  - python -m pylama
  - python -m isort --check-only --diff .
  - python -m yamllint tests/good/*.yaml tests/bad/*.yaml docker-compose.yml .yamllint .travis.yml .cfnlintrc
  - python -m mypy .

notifications:
  email: false
