---
dist: bionic
language: python
python:
  - 3.7
  - 3.6

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pipenv sync --dev

script:
  - pipenv run pytest
  - pipenv run black --check --verbose .
  - pipenv run pylama
  - pipenv run isort --recursive --check-only --diff
  - pipenv run yamllint tests/good/*.yaml tests/bad/*.yaml docker-compose.yml .yamllint .travis.yml .cfnlintrc
  - pipenv check
  - pipenv check --unused rules || true

notifications:
  email: false
