---
dist: xenial
language: python
python:
  - 3.7
  - 3.6

install:
  - pip install -r requirements.txt

script:
  - pytest
  - black --check --verbose .
  - pylama
  - isort --recursive --check-only --diff
  - yamllint tests/good/*.yaml tests/bad/*.yaml docker-compose.yml .yamllint .travis.yml .cfnlintrc
  - pip list --outdated


notifications:
  email: false
