---
dist: bionic
language: python
python:
  - 3.8

install:
  - python -m pip install -r ./requirements/dev.txt

script:
  - pytest
  - black --check --verbose .
  - pylama
  - isort --check-only --diff .
  - yamllint tests/good/*.yaml tests/bad/*.yaml docker-compose.yml .yamllint .travis.yml .cfnlintrc

notifications:
  email: false
