---
name: Tests
# yamllint disable rule:truthy
on: [push, workflow_dispatch]
# yamllint enable

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install requirements
        run: |
          python -m pip install -r ./requirements/dev.txt
        id: req-installed
      - name: Run pytest
        run: |
         python -m pytest
      - name: Run black
        run: |
          python -m black --check --verbose .
        if: ${{ !cancelled() && steps.req-installed.outcome == 'success' }}
      - name: Run pylama
        run: |
          python -m pylama
        if: ${{ !cancelled() && steps.req-installed.outcome == 'success' }}
      - name: Run isort
        run: |
          python -m isort --check-only --diff .
        if: ${{ !cancelled() && steps.req-installed.outcome == 'success' }}
      - name: Run yamllint
        run: |
          find ./ -type f \( -regex ".*\.ya?ml" -o -iname ".yamllint" -o -iname ".cfnlintrc" \) \
            -print0 | xargs -0 \
            python -m yamllint --strict
        if: ${{ !cancelled() && steps.req-installed.outcome == 'success' }}
      - name: Run mypy
        run: |
          python -m mypy .
        if: ${{ !cancelled() && steps.req-installed.outcome == 'success' }}
      - uses: aexeagmbh/gh-actions-ntfy-slack@main
        with:
          job-status: ${{ job.status }}
          slack-channel: ${{ secrets.SLACK_CHANNEL }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
        if: always()
